# Generated by Django 5.0.3 on 2024-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_booking_contact_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('CheckOut', 'CheckOut'), ('confirmed', 'Confirmed'), ('cancled', 'Cancled')], max_length=30),
        ),
    ]
