# Generated by Django 5.0.3 on 2024-05-04 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 16, 33, 24, 357485, tzinfo=datetime.timezone.utc)),
        ),
    ]
