# Generated by Django 3.2 on 2024-05-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_booking_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
